# -*- coding: utf-8 -*-
"""ZeroShotClassification_HuggingFace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/179qti6FnVU1h9Bvhlh81uwu796gYMTwZ
"""



from transformers import pipeline
classifier = pipeline(
                      task="zero-shot-classification",
#                       device=0,
                      model="facebook/bart-large-mnli"
                    )

text = """

"""
classifier(text,["positive","negative",'neutral'],multi_class=True)

